### ISSUE TITLE
Document the behavior of the current CGU partitioning algorithm

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/wg-incr-comp#2]
Ideally, some or all of this information would end up in the [Rustc Dev Guide](https://rustc-dev-guide.rust-lang.org/).

In particular, it would be good to have documented how up/down stream instantiations are handled. Suppose we have two crates, `a` and `b` of which `b` has a dependency on `a`. We should test the following combinations and report what how these scenarios are handled:

Crate a | Crate b
-- | --
Non-generic function | Uses once in a module
Non-generic function | Uses in two different modules
Non-generic #[inline] function | Uses once in a module
Non-generic #[inline] function | Uses in two different modules
Generic function | Uses once in a module
Generic function | Uses in two different modules
Generic #[inline] function | Uses once in a module
Generic #[inline] function | Uses in two different modules

Are the functions instantiated upstream (in crate `a`) or downstream (in crate `b`). If downstream, are they instantiated in multiple CGUs or once and shared? 

You should be able to gather that data by writing an example and compiling with `RUSTC_LOG=rustc_mir::src::monomorphize::partitioning` and then looking for the output from [this line](https://github.com/rust-lang/rust/blob/eb9e7c357e26bf41c47661720e46f4498de32b83/compiler/rustc_mir/src/monomorphize/partitioning/mod.rs#L169).

**Comment by arora-aman** [comment]
I should probably have a PR up for rustc_dev_guide by tomorrow.

I did my testing and the results are here: https://github.com/arora-aman/incr-compile-docs/blob/master/overall_results.md

--

The RUSTC_LOG needs to be `rustc_mir::monomorphize::partitioning`. 

I did my testing with rustc compiled with commit 
```
commit 4f66117945df3b21e46ee9013e1c8a88f4b27842 (HEAD, origin/master, origin/HEAD)
Merge: 51f79b618d4 af331a2d015
Author: bors <bors@rust-lang.org>
Date:   Thu Sep 3 00:24:50 2020 +0000
```

**Comment by wesleywiser** [comment]
That looks great @arora-aman! If you're looking for where to record this in the rustc-dev-guide, somewhere around here might be good https://rustc-dev-guide.rust-lang.org/backend/monomorph.html?highlight=codegen,unit#collection 

Feel free to cc me on that PR.

**Comment by arora-aman** [comment]
Will do, thanks!
